version: "2"
checks:
  file-lines:
    config:
      threshold: 1000
  method-lines:
    config:
      threshold: 100
exclude_patterns:
  - "AutomatedTests/"
  - "**/*.js"
  - ".mvn/"
  - ".github/"
  - ".env"
  - ".env.template"
  - "src/test"
