security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
pcss:
  host: ${ORDS_HOST}
  username: ${ORDS_USERNAME}
  password: ${ORDS_PASSWORD}
  ords-read-timeout: ${ORDS_READ_TIMEOUT}

