security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}

test:
  password: ${BASIC_AUTH_PASS}
  username: ${BASIC_AUTH_USER}
  api-host-civil: ${API_HOST_CIVIL}
  api-host-criminal: ${API_HOST_CRIMINAL}
  api-host-common: ${API_HOST_COMMON}
