kind: Template
apiVersion: v1
metadata:
  name: ${COMPONENT_NAME}
  namespace: ${OC_NAMESPACE}-tools
  description: Deployment template for the ${COMPONENT_NAME}

labels:
  app.kubernetes.io/name: ${COMPONENT_NAME}
  app.openshift.io/runtime: ${RUNTIME}

parameters:

- name: COMPONENT_NAME
  description: The application name that each component is part of
  required: false
  value: influxdb

- name: OC_NAMESPACE
  description: The OpenShift namespace prefix
  required: false
  # Below value must be changed as per gold cluster oc nameplate
  value: 17b24e

- name: RUNTIME
  description: The application name that each component is part of
  required: false
  value: influxdb

objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ${COMPONENT_NAME}
    namespace: ${OC_NAMESPACE}-tools
    labels:
      app: ${COMPONENT_NAME}
  data:
    influxdb.conf: |
      [meta]
        dir = "/var/lib/influxdb/meta"

      [data]
        dir = "/var/lib/influxdb/data"
        engine = "tsm1"
        wal-dir = "/var/lib/influxdb/wal"

      # Configure the graphite api
      [[graphite]]
      enabled = true
      bind-address = ":2003" # If not set, is actually set to bind-address.
      database = "jmeter"  # store graphite data in this database

      [admin]
      enabled = true
      bind-address = ":8083"
      https-enabled = false
      database = "jmeter"

- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: ${COMPONENT_NAME}
    namespace: ${OC_NAMESPACE}-tools
    labels:
      app.kubernetes.io/part-of: jmeter
      metrics: ${COMPONENT_NAME}
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${COMPONENT_NAME}
          from:
            kind: ImageStreamTag
            namespace: ${OC_NAMESPACE}-tools
            name: influxdb:1.8.9
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      metrics: ${COMPONENT_NAME}
    template:
      metadata:
        creationTimestamp: null
        labels:
          metrics: ${COMPONENT_NAME}
      spec:
        volumes:
          - name: ${COMPONENT_NAME}-data
            emptyDir: {}
        containers:
        # Below value must be changed as per gold cluster oc imagestream url
          - image: >-
              image-registry.openshift-image-registry.svc:5000/${OC_NAMESPACE}-tools/influxdb:1.8.9
            name: influxdb
            resources: {}
            terminationMessagePath: /dev/termination-log
            env:
              - name: INFLUXDB_UDP_ENABLED
                value: 'true'
              - name: INFLUXDB_UDP_BIND_ADDRESS
                value: ':8087'
              - name: INFLUXDB_UDP_DATABASE
                value: udp
            ports:
              - containerPort: 8086
                protocol: TCP
              - containerPort: 8087
                protocol: UDP
              - containerPort: 8083
                protocol: TCP
            imagePullPolicy: Always
            volumeMounts:
              - name: ${COMPONENT_NAME}-data
                mountPath: /var/lib/influxdb
            terminationMessagePolicy: File
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler

- kind: Service
  apiVersion: v1
  metadata:
    name: ${COMPONENT_NAME}
    namespace: ${OC_NAMESPACE}-tools
    labels:
      app: ${COMPONENT_NAME}
  spec:
    ports:
      - name: http
        protocol: TCP
        port: 8083
        targetPort: 8083
      - name: api
        protocol: TCP
        port: 8086
        targetPort: 8086
      - name: graphite
        protocol: TCP
        port: 2003
        targetPort: 2003
    selector:
      metrics: ${COMPONENT_NAME}


