name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run:  echo ${{secrets.TEST_STARTER_URL}} | sed 's/./& /g' 
